=========================================================
--give all details like procedures and warning
==========================================================
SELECT TOP (1000) [cst_id]
      ,[cst_key]
      ,[cst_firstname]
      ,[cst_lastname]
      ,[cst_marital_status]
      ,[cst_gender]
      ,[cst_create_date]
  FROM [DATAWAREHOUSE].[bronze].[crm_cust_info]

-- similarly make for all the 6 databases created
--then create an integration model in draw.io

CREATE TABLE silver.crm_cust_info (
cst_id INT,
cst_key NVARCHAR (50),
cst_firstname NVARCHAR (50),
cst_lastname NVARCHAR (50),
cst_marital_status NVARCHAR (50),
cst_gender NVARCHAR (50),
cst_create_date DATE,
dwh_create_date DATETIME2 DEFAULT GETDATE() --METADATA COLUMN- ADDED by data engineers for info not generated by original source
);

-- chcek quality of bronze layer
/* check for nulls or duplicates in primary key
expectation- no result
select
cst_id,
count (*)
from bronze.crm_cust_info
group by cst_id
having count (*) > 1 checking duplicates and nulls */

SELECT *
FROM bronze.crm_cust_info
WHERE Cst_id = 29466 -- we will use window function 

SELECT *,
ROW_NUMBER () OVER (PARTITION BY cst_id ORDER BY CST_CREATE_DATE DESC) AS flag_last
FROM bronze.crm_cust_info;
--no duplicates using the below query
SELECT *
FROM (
SELECT *,
ROW_NUMBER () OVER (PARTITION BY cst_id ORDER BY CST_CREATE_DATE DESC) AS flag_last
FROM bronze.crm_cust_info
)T WHERE flag_last = 1

--check for unwanted strings, spaces in names
SELECT cst_firstname
FROM bronze.crm_cust_info
WHERE cst_firstname != TRIM(cst_firstname);

SELECT cst_lastname
FROM bronze.crm_cust_info
WHERE cst_lastname != TRIM(cst_lastname);

SELECT cst_gender
FROM bronze.crm_cust_info
WHERE cst_gender != TRIM(cst_gender) -- no issues here

-- resolution
SELECT
cst_id,
cst_key,
TRIM(cst_firstname) as cst_firstname,
TRIM(CST_LASTNAME) AS cst_lastname,
cst_marital_status,
cst_gender,
cst_create_date
FROM (
    SELECT *,
    ROW_NUMBER () OVER (PARTITION BY cst_id ORDER BY CST_CREATE_DATE DESC) AS flag_last
    FROM bronze.crm_cust_info
    )T WHERE flag_last = 1

-- DATA STANDARDISATION AND CONSISTENCY
SELECT DISTINCT CST_GENDER
FROM BRONZE.crm_cust_info
--MAKE IT A RULE NOT TO USE ABBREVIATIONS

SELECT
cst_id,
cst_key,
TRIM(cst_firstname) as cst_firstname,
TRIM(CST_LASTNAME) AS cst_lastname,
cst_marital_status,
CASE WHEN UPPER(TRIM(cst_gender)) = 'F' Then 'Female' --in case there are any lower case values we will be able to catch that
     WHEN UPPER(TRIM(cst_gender)) = 'M' THEN 'Male' -- also using trim in case there are spaces infront of the gender
     ELSE 'n/a'
END cst_gender,
cst_create_date
FROM (
    SELECT *,
    ROW_NUMBER () OVER (PARTITION BY cst_id ORDER BY CST_CREATE_DATE DESC) AS flag_last
    FROM bronze.crm_cust_info
    )T WHERE flag_last = 1


--Same for marital status
SELECT DISTINCT CST_marital_status
FROM BRONZE.crm_cust_info

SELECT
cst_id,
cst_key,
TRIM(cst_firstname) as cst_firstname,
TRIM(CST_LASTNAME) AS cst_lastname,
CASE WHEN UPPER(TRIM(cst_marital_status)) = 'S' Then 'Single' --in case there are any lower case values we will be able to catch that
     WHEN UPPER(TRIM(cst_marital_status)) = 'M' THEN 'Married' -- also using trim in case there are spaces infront of the gender
     ELSE 'n/a'
END cst_marital_status,
CASE WHEN UPPER(TRIM(cst_gender)) = 'F' Then 'Female' --in case there are any lower case values we will be able to catch that
     WHEN UPPER(TRIM(cst_gender)) = 'M' THEN 'Male' -- also using trim in case there are spaces infront of the gender
     ELSE 'n/a'
END cst_gender,
cst_create_date
FROM (
    SELECT *,
    ROW_NUMBER () OVER (PARTITION BY cst_id ORDER BY CST_CREATE_DATE DESC) AS flag_last
    FROM bronze.crm_cust_info
    )T WHERE flag_last = 1


--INSERT INTO SILVER LAYER
INSERT INTO silver.crm_cust_info (cst_id, cst_key, cst_firstname, cst_lastname, cst_marital_status, cst_gender, cst_create_date)
SELECT
cst_id,
cst_key,
TRIM(cst_firstname) as cst_firstname,
TRIM(CST_LASTNAME) AS cst_lastname,
CASE WHEN UPPER(TRIM(cst_marital_status)) = 'S' Then 'Single' --in case there are any lower case values we will be able to catch that
     WHEN UPPER(TRIM(cst_marital_status)) = 'M' THEN 'Married' -- also using trim in case there are spaces infront of the gender
     ELSE 'n/a'
END cst_marital_status,
CASE WHEN UPPER(TRIM(cst_gender)) = 'F' Then 'Female' --in case there are any lower case values we will be able to catch that
     WHEN UPPER(TRIM(cst_gender)) = 'M' THEN 'Male' -- also using trim in case there are spaces infront of the gender
     ELSE 'n/a'
END cst_gender,
cst_create_date
FROM (
    SELECT *,
    ROW_NUMBER () OVER (PARTITION BY cst_id ORDER BY CST_CREATE_DATE DESC) AS flag_last
    FROM bronze.crm_cust_info
    )T WHERE flag_last = 1


--rerun quality checks in the silver layer changing brinze.crm_cust_infor to silver.crm_cust_info
--clean and load -- requires other tables as well
-- once that is done- we use truncate option because everytime you run it data will be duplicated
PRINT '>> TRUNCATING DATA INTO: SILVER TABLE';
TRUNCATE TABLE silver.crm_cust_info;
PRINT '>> INSERTING DATA INTO: SILVER TABLE';
INSERT INTO silver.crm_cust_info (cst_id, cst_key, cst_firstname, cst_lastname, cst_marital_status, cst_gender, cst_create_date)
SELECT
cst_id,
cst_key,
TRIM(cst_firstname) as cst_firstname,
TRIM(CST_LASTNAME) AS cst_lastname,
CASE WHEN UPPER(TRIM(cst_marital_status)) = 'S' Then 'Single' --in case there are any lower case values we will be able to catch that
     WHEN UPPER(TRIM(cst_marital_status)) = 'M' THEN 'Married' -- also using trim in case there are spaces infront of the gender
     ELSE 'n/a'
END cst_marital_status,
CASE WHEN UPPER(TRIM(cst_gender)) = 'F' Then 'Female' --in case there are any lower case values we will be able to catch that
     WHEN UPPER(TRIM(cst_gender)) = 'M' THEN 'Male' -- also using trim in case there are spaces infront of the gender
     ELSE 'n/a'
END cst_gender,
cst_create_date
FROM (
    SELECT *,
    ROW_NUMBER () OVER (PARTITION BY cst_id ORDER BY CST_CREATE_DATE DESC) AS flag_last
    FROM bronze.crm_cust_info
    )T WHERE flag_last = 1

--create stored procedure
/*CREATE OR ALTER PROCEDURE siler.load_silver AS
BEGIN
PRINT '>> TRUNCATING DATA INTO: SILVER TABLE';
TRUNCATE TABLE silver.crm_cust_info;
PRINT '>> INSERTING DATA INTO: SILVER TABLE';
INSERT INTO silver.crm_cust_info (cst_id, cst_key, cst_firstname, cst_lastname, cst_marital_status, cst_gender, cst_create_date)
SELECT
cst_id,
cst_key,
TRIM(cst_firstname) as cst_firstname,
TRIM(CST_LASTNAME) AS cst_lastname,
CASE WHEN UPPER(TRIM(cst_marital_status)) = 'S' Then 'Single' --in case there are any lower case values we will be able to catch that
     WHEN UPPER(TRIM(cst_marital_status)) = 'M' THEN 'Married' -- also using trim in case there are spaces infront of the gender
     ELSE 'n/a'
END cst_marital_status,
CASE WHEN UPPER(TRIM(cst_gender)) = 'F' Then 'Female' --in case there are any lower case values we will be able to catch that
     WHEN UPPER(TRIM(cst_gender)) = 'M' THEN 'Male' -- also using trim in case there are spaces infront of the gender
     ELSE 'n/a'
END cst_gender,
cst_create_date
FROM (
    SELECT *,
    ROW_NUMBER () OVER (PARTITION BY cst_id ORDER BY CST_CREATE_DATE DESC) AS flag_last
    FROM bronze.crm_cust_info
    )T WHERE flag_last = 1
END
EXEC siler.load_silver */
--then do error testing 
